### ISSUE TITLE
Should there be a `vrdisplaypresenterror` event?

### ISSUE THREAD

**Issue by cvan** [w3c/webvr#109]
For measure, the [Fullscreen API](https://fullscreen.spec.whatwg.org/) has the following events:
- [`fullscreenchange`](https://fullscreen.spec.whatwg.org/#handler-document-onfullscreenchange)
- [`fullscreenerror`](https://fullscreen.spec.whatwg.org/#handler-document-onfullscreenchange)

For the WebVR API, we have
- [`vrdisplaypresentchange`](https://w3c.github.io/webvr/#window-vrdisplaypresentchange-event)
- <s>`vrdisplaypresenterror`</s> - should we support this?

If someone calls `vrDisplay.requestPresent()` and it rejects (or possibly if it throws too), I would hope for an event to fire. Otherwise, I'll have to rely on Promises entirely and interface with these methods directly, at which point the events become not that useful.

**Comment by toji** [comment]
To be honest I'd prefer to reply on the promise entirely, but that's not a viable option for `vrdisplaypresentchange`. The issue is that the browser may force you our of VR presentation at any time for any reason (most likely the user hit some explicit "Exit WebVR" button, like tapping `esc` to exit fullscreen). We can add an error event, certainly, but I don't see it filling an explicit need like the `presentchange` event does.

**Comment by toji** [comment]
Brought this up at the WebVR F2F in Kirkland. Room agreed with assessment above. Closing as will not implement.
