### ISSUE TITLE
Could use some more clarity on requestPresent

### ISSUE THREAD

**Issue by ssylvan** [w3c/webvr#137]
Currently requestPresent seems to handle most kinds of invalid arguments by rejecting the promise (e.g. too many layers, null source, etc.). It doesn't specify what happens if the user passes in a source that isn't a canvas. Do we throw an exception? Or should that also cause the promise to be rejected?

The spec also states that the promise is rejected if the bounds have the wrong number of elements (i.e not 0 or 4), but doesn't say what happens if the values in those elements are not in the right numeric range (0.0 to 1.0). Do we throw an exception, reject the promise or maybe clamp the values?

**Comment by toji** [comment]
I think that in the cases where we're returning a promise anyway we should always communicate errors as a promise rejection, even in cases where the spec has not anticipated the error. (There will always be random "Browser implementation detail failed" sorts of errors that shouldn't be communicated in the spec.) Otherwise as a developer I'd need to both handle the promise AND wrap the call in a try/catch in order to properly handle all possible failure states.

Besides, I think if a promise fails without an explicit failure handler specified the default behavior is to throw and exception anyway. That means that if you prefer exception handling to promise callbacks you can still work with the API effectively.

**Comment by ssylvan** [comment]
Cool, makes sense to me! Thanks!
