### ISSUE TITLE
Clarify what happens when submitFrame is called at the wrong time

### ISSUE THREAD

**Issue by brianchirls** [w3c/webvr#138]
It may be useful to clarify that `submitFrame` should not be called when `isPresenting` is `false` on a given `VRDisplay` and what should happen if it is. I believe Chrome logs a warning to the console but that there is no other effect. No error is thrown so it doesn't break the rAF loop. I believe this is the correct approach.

It may also be worth considering what happens if `submitFrame` is called outside of the `requestAnimationFrame` callback for the corresponding `VRDisplay` (or in the global rAF callback). Is there any reason doing that is a good idea? Would it specifically cause a problem? Is this something we want to try to recover from gracefully when someone just writes buggy code or do we want to fail early? Perhaps a console warning is in order and sufficient?

Possibly related to #69.

cc @klausw

**Comment by toji** [comment]
Closing since this is planned to be addressed in 2.0. If anyone has issues with the 2.0 proposal, please file a new issue. For details see: 
https://github.com/w3c/webvr/blob/master/explainer.md#main-render-loop

**Comment by SamiraAtMicrosoft** [comment]
Requesting to reopen this ticket to be addressed in v1.1.
Given that we are a ways from completing v2.0 of the spec, we must provide developers a consistent manner in which to notify them of an erroneous call to submitFrame() when not in presentation mode.

Currently Edge throws a SecurityError. Instead of this, we propose:
-	InvalidStateError.
Alternatively we can not throw any error. Either way, a meaningful console warning message should be provided.

What are your thoughts about adopting either of the two options?

**Comment by toji** [comment]
Chrome is currently providing a console warning in the case that `submitFrame` is called either when not in presentation mode or not in a rAF callback. See https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/vr/VRDisplay.cpp?l=463 for the code in question.

I'm fine with that approach, and I think we went that route to avoid breaking pages that would otherwise work because they were calling `submitFrame` all the time, whether it was appropriate or not. I wouldn't object to changing it to an error, though, if there was a compelling reason to do so. Please note, however, at this point such a change wouldn't show up in Chrome until M60 (Stable in early August.)
