### ISSUE TITLE
bitmaprenderer instead of submitFrame?

### ISSUE THREAD

**Issue by bfgeek** [w3c/webvr#141]
A few of us (cc/ @junov ) were talking about `submitFrame`; the specific use-case was if an author was using canvas-context with a `VRDisplay` and a `HTMLCanvasElement`.

E.g.

```js
const display = getVRDisplayMagically();
const canvas = document.getElementById('canvas');
const gl = canvas.getContext('webgl2');

display.requestAnimationFrame(drawVRFrame);
requestAnimationFrame(drawMainFrame);

function drawVRFrame() {
  gl.bunchOfDrawCalls();
  dsiplay.submitFrame();
}

function drawMainFrame() {
  gl.bunchOfDrawCalls();
  // changes will get picked up at vsync.
}
``` 

One thing to consider is using the OffscreenCanvas proposal to support this, i.e.
```js
const display = getVRDisplayMagically();
const canvas = new OffscreenCanvas(width, height);
const gl = canvas.getContext('webgl2');

const mainCanvas = document.getElementById('canvas');
const vrCanvas = new OffscreenCanvas(width, height);

display.requestPresent(new VRFOVLayer(vrCanvas));

const mainCanvasContext = mainCanvas.getContext('bitmaprenderer');
const vrCanvasContext = vrCanvas.getContext('bitmaprenderer');

requestAnimationFrame(drawMainFrame);
vrCanvas.requestAnimationFrame(drawVRFrame);

function drawVRFrame() {
  gl.bunchOfDrawCalls();
  vrCanvasContext.transferImageBitmap(canvas.transferFromImageBitmap());
  // changes will get picked up at vr-vsync.
}

function drawMainFrame() {
  gl.bunchOfDrawCalls();
  mainCanvasContext.transferImageBitmap(canvas.transferFromImageBitmap());
  // changes will get picked up at vsync.
}
```

Note I've used `OffscreenCanvas` here but not sure if `transferFromImageBitmap` would work for a detached `HTMLCanvasElement`.

@junov can confirm.

Thoughts?

**Comment by junov** [comment]
Looking at those two code examples, it is not clear to me what problem you are trying to solve by using OffscreenCanvas.

**Comment by bfgeek** [comment]
Removing the `submitFrame` api call.

**Comment by junov** [comment]
So the objective is solely to reduce the API surface? Okay well that works. The memory footprint is essentially the same since under the hood, submitFrame would cause a snapshot to be retained..

**Comment by bfgeek** [comment]
Thanks right. Trying to keep the number of ways of doing things to a sane level :)

**Comment by RafaelCintron** [comment]
My strong preference would be to avoid requiring offscreen canvas in order to use WebVR.  Using offscreen canvas should be optional.

**Comment by bfgeek** [comment]
This doesn't require OffscreenCanvas for WebVR.

This is for the specific use-case where you want to display two different images from the same GL context (e.g. one for VRDisplay, and another for a HTMLCanvas - which have different render outputs).

Which from my understanding is why `submitFrame` was added instead of just capturing the output before vsync like normal canvas does.

For this specific use-case it seems like we should be able to use OffscreenCanvas to simplify the API?

**Comment by junov** [comment]
It is still unclear to me why submitFrame() was necessary in the first place. As long as all the animations are driven through rAF, everything should be fine (no flickering due to overwrites or anything like that).  This is because the processing model for the event loop guarantees that no script can be executed between the invocation of the rAF callback and the graphics update that captures the results of the rAF callback.  This is how window.requestAnimationFrame is spec'ed .  As long as WebVR's rAF behaves similarly, implementors should not need to worry about synchronization issues between the two captures.

The important conditions implementations need to respect:
1) rAF callback execution + changes getting picked-up for display = an atomic bloc. Nothing can get between them.
2) When rAF is called from whithin a rAF callback, it must be garanteed that the next frame cannot be picked-up without running the pending rAF callback. 


For reference: https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-processing-model
Look at step 7, substep 10 + 12:  window.rAF already respects both necessary conditions.

As for WebVR's rAF, it is currently under-spec'ed.  We need to define more clearly how it interacts with the browsing context's event loop processing model IMHO.

**Comment by toji** [comment]
The event loop has been overhauled and clarified in the explainer at this point, one consequence of which was dropping `submitFrame`. At this point the API in the explainer should account for most of this feedback, so I'm closing the issue as a housekeeping measure.
