### ISSUE TITLE
Describe hand property on Gamepad object

### ISSUE THREAD

**Issue by brianchirls** [w3c/webvr#158]
I don't see this listed anywhere in the [Gamepad spec](https://w3c.github.io/gamepad/) or in here. Presumably, it should be under Gamepad Interface extension.

I see a `hand` property on `Gamepad` objects, which is either "left", "right" or "". It's not clear to me how that value is determined.

**Comment by toji** [comment]
This is currently described in the [Gamepad Extensions spec](https://w3c.github.io/gamepad/extensions.html#gamepadhand-enum), which we hope to merge back into the standard Gamepad spec at some point. In the meantime it does cause a little bit of confusion, which I apologize for.

**Comment by brianchirls** [comment]
Okay, I see that. Thanks.

The hand selection is still not clear. Is it possible to elaborate on that? In practice, in the browser(s), I'm not seeing consistent behavior there, and it's impossible to know whether the browser is misbehaving.

**Comment by toji** [comment]
What's the behavior you're seeing? At a high level, what I expect you should see in Chrome is:

 - Any "normal" gamepad (XBox, PS4, etc) will have an empty string in hand, because it's not inherently associated with either hand.
 - The Daydream controller should return whichever hand you have set in the Daydream settings. (Known bug: Does not refresh if setting is changed while the page is open)
 - Oculus Touch controllers will report left or right consistently for each device, since they are shaped in such a way that they can only really be held in one hand.
 - Vive wands may report either hand or empty string, and the hand may change at runtime. This is because the controllers can be held in either hand and OpenVR is only giving a best guess estimate for the hand at any point. This is usually a really good guess, but it takes a moment to stabilize, so the controllers start most VR sessions with no hand associated. Doing things like swapping hands in a play session will also cause a delayed update.

So, given all that the appropriate way for an app to handle handedness is to check it each frame, and be robust to cases where the hand is unknown. For some devices (Touch) that won't matter, but if you don't treat it that way less static devices like the Vive wands will fail in creative ways.

**Comment by brianchirls** [comment]
Okay, this is extremely helpful, and it describes what I'm seeing. Thank you.

I think it would be good to have a note in the appropriate section of the spec that the hand value could change at any time and is determined by the particular hardware.

**Comment by toji** [comment]
Good call, I'll work on updating that.
