### ISSUE TITLE
Add a function to get the user-preferred forward direction

### ISSUE THREAD

**Issue by mikebolt** [w3c/webvr#167]
I tried WebVR for the first time yesterday, and I was surprised that the default forward direction was not towards my monitor. I tried the A-Frame hello world demo, and the colorful objects were located directly to my right instead of in front of me, yet they show up in front of the camera in the 2D version. This issue can't be blamed on A-Frame or Three.js if they do not know the direction of my monitor in my VR coordinate space.

I think having a "natural" default orientation is vital for a good WebVR experience. Users will have to switch between wearing the headset and using their desktop, and when they do so the default view should match the user's expected orientation when they put on their headset.

The `resetPose()` method of VRDisplay helps address this problem by allowing developers to easily orient the coordinate system to the user's current pose. This is sufficient for current mobile VR applications, because the coordinate systems are all relative and not tied to a world reference point between experiences. However, with desktop VR the coordinate system will often be the same between experiences due to mounted sensors or cameras. Users probably don't want to re-select their preferred forward direction every time they enter a webVR application.

Unfortunately, this API would open up another tracking hole, where websites could identify users by querying their preferred orientation. This could be mitigated by requiring the preferred forward direction to be level with gravity, and by only allowing (for example) 8 options 45 degrees apart. This setting could be configured using a 2D API that shows the current location of the headset, lighthouses, and any other tracked objects. A 3D interface would also work, but would likely be more difficult for browser developers to implement. Ideally the underlying VR SDK would provide this preference whenever it makes sense so that the browser would not need to provide a user setting interface.

Alternatively, if the VR SDKs standardize their coordinate systems so that "forward" is always some agreed-upon vector, then this is not necessary. The browsers could even convert device-specific coordinate systems into the standard coordinate system whenever possible. This may be mentioned once in the current draft, but it is not 100% clear:

> orientation Orientation of the sensor as a quaternion. The orientation yaw (rotation around the Y axis) is relative to the initial yaw of the sensor when it was first read or the yaw of the sensor at the point that resetPose() was last called. An orientation of [0, 0, 0, 1] is considered to be "forward". ...

**Comment by toji** [comment]
I'm going to guess your scenario where everything appeared off to one side was one of two things: Either your headset started on your desk pointing off one side, so it assumed that was the natural forward vector, or you have a "Room Scale" setup who's default forward vector points off to one side. In either case I'd argue that the API is doing the right thing. 

"Forward" is a very fuzzy concept, and is highly dependent on what your hardware is capable of. With mobile headsets (GearVR, Daydream) forward tends to be "Whatever direction you were looking when the VR app started." though it can be reset manually by the user. And really, what else would make sense? There's no natural external point of reference to use to say "this is forward" unless you wanted to do something silly like say "North is always the forward vector", which is a terrible idea. Most people will be looking "forward" when they first put on the headset, though, so it makes sense to use that initial position as the default and let the user override as necessary.

Most desktop headsets have a mode that works like that as well, and we expose it for compatibility with mobile devices. They may also external trackers in the room, which are presumably immobile. In that case we can always know where the HMD is relative to the trackers and thus choose a consistent forward vector relative to them. Fortunately the existing native APIs already handle this for us, so we simply defer to them in the "room scale" case. The user may have explicitly NOT set forward to point towards their monitor, or any other obvious object in the room, though. This is actually very common with the Vive, which actively tries to point your room coordinates away from the PC monitor to help with cable management. Hopefully, though, since the user set it up like that it's not surprising behavior to them.

In either case, there's not much the WebVR API can or should do beyond simply saying "forward is negative Z. We have no idea how that relates to your physical environment." If for whatever reason you're consistently getting a forward vector that's not what you want AND you can't control that through the native VR system for some reason I guess it would be possible to write a browser extension that pre-multiplied all the output matrices/quaternions to your preferred orientation, but that doesn't sound like something the API should be doing.

Finally, consider that the long-term expectation is that we'll have browsers that operate in VR as well, which will reduce the amount of times you need to put on and remove the headset while browsing. In such an environment the forward vector of the scene and the 2D browsing interface would always be consistent, so it becomes less of an issue.

**Comment by mikebolt** [comment]
Thanks for the response. Those are all good points.

I did some more testing. I ran the steam room setup with a long play area, a wide play area, and with the "standing room only" option. For the room-scale setups I pointed the controller at the monitor correctly as instructed. For each setup I tested both your Chromium build and Firefox Nightly. I also tested with the headset facing directly at the monitor when entering VR and with the headset facing to the right of the monitor when entering VR. There was no difference between browsers, and the orientation of the headset when entering VR also made no difference. The "standing room only" mode worked correctly, but when I used the room-scale setup it was incorrect. With a long play area, with the monitor at a short end of the rectangular play area, the objects appeared to the left of the monitor (I'm not sure why it was left this time). With a wide play area the objects were opposite the monitor. It seems like the Vive SDK is setting the forward direction to be anything except the direction of the monitor, for the reason you mentioned. This leaves 3 possibilities for the direction of the monitor if you assume that it is aligned with the play area.

I suppose this is something that developers will need to consider on a case-by-case. If the user should not expect to move around, then developers can set up the coordinate system as if it were a mobile or standing experience. If the user is supposed to move around, then the default coordinate system should make sense anyway, and developers should guide users to the point of interest as necessary. The A-Frame hello world demo is very basic and does not account for these things.
