### ISSUE TITLE
Feedback: VRDisplay:submitFrame() should be dropped

### ISSUE THREAD

**Issue by travisleithead** [w3c/webvr#170]
Having an explicit commit API means that the failure mode (for not calling the API) is to drop a frame. This is not the way canvas rendering typically works in the web platform. Rather, while script is in control, drawing instructions are sent to the canvas, and when the script finally yields (e.g., when the requestAnimationFrame callback ends) then there is an _implicit_ frame commit/submit. If no drawing commands are submitted to a canvas, then its state isn't changed and the last frame's contents can be re-rendered.

I believe that the spec should be changed so that frames are implicitly submitted to the vrDisplay after the vrDisplay's requestAnimationFrame callback completes, and the submitFrame() API should be removed. This also could help address #69.

**Comment by spite** [comment]
But in the web there's typically just one path: the canvas ends on screen. With submitFrame we have the possibility to "draw" to the HMD and then continue rendering for the screen, like in the Advanced Mirroring example https://webvr.info/samples/07-advanced-mirroring.html. Granted, it's a very specific use case, but it's nice to have.

**Comment by kearwood** [comment]
Having a separate submitFrame call is essential to maintain low latency rendering.  In many rendering engines, there will be more processing after the frame is submitted, such as analyzing the frame for screen space reflectis and hdr levelling histograms.  We do not want to delay the frame submission when it is ready to be submitted.  Even if content can finish all work before the next vsync cycle, submitting the frame as soon as it's ready enables the underlying optimizations in Oculus and OpenVR's compositors to work more effectively.

Additionally, if content is unable to render a frame, such as due to assets not loading in time, it is essential that the last rendered frame does not implicitly get submitted at the end of RAF, as this will break the asynchronous time/space warp reprojection.

**Comment by toji** [comment]
The reasons cited above are why the API is in place right now, but I'm not opposed to taking a moment to review that decision as part of the 1.2 refactor to see if there's a better way to handle it. Whatever route we take must have the ability to control presentation on external displays and ideally limit latency.

**Comment by travisleithead** [comment]
> We do not want to delay the frame submission when it is ready to be submitted. Even if content can finish all work before the next vsync cycle, submitting the frame as soon as it's ready enables the underlying optimizations in Oculus and OpenVR's compositors to work more effectively.

I'm not sure I buy this as a real concern. Let's say the WebVR application wants to submit a frame ASAP. So, within a callback at time 'p' it starts issuing rendering commands. At time 't' it calls submit and then continues doing post-submit operations until time 'q'. Then there is a yield, and the process repeats:
`[ p0 .. t0 .. q0.. | p1 .. t1 .. q1.. | ... | pn .. tn .. qn ]`

Let's say the time interval between t0 and t1 (or any interval) is 'i'.

Now if you shuffle work around and implicit-commit at the end, your process might be: do 'p' work, do 'q' work, then when your callback ends, 't' happens. Repeat:
`[ p0 .. q0 .. t0 .. | p1 .. q1 .. t1 .. | ... | pn .. qn .. tn ]`

Note the time interval between t0 and t1 is the same as 'i'. From the GPU's standpoint, both scenarios result in frame getting sent to the GPU at interval 'i', regardless of how you arrange the workload in the callback.

**Comment by toji** [comment]
Closing since this is planned to be addressed in 2.0. If anyone has issues with the 2.0 proposal, please file a new issue. For details see: https://github.com/w3c/webvr/blob/master/explainer.md#main-render-loop
