### ISSUE TITLE
Use xr namespace

### ISSUE THREAD

**Issue by AlbertoElias** [w3c/webvr#199]
I'm a bit worried about bringing this up again, I know there was already a long conversation on the mailing list a while back about it. But with the announcement of OpenXR by Khronos (which WebVR will probably support) and the fact that 2.0 seems to be more ready to support augmented/mixed reality, and with the excuse of 2.0 and the naming issue, it seems like it could be relevant again.

I think would be a good idea to share names with Khronos maybe preventing confusion in the future, as well as my point about 2.0.

**Comment by toji** [comment]
I've always said that if people are complaining about how short-sighted the name WebVR was ten years from now I'll be perfectly happy, because it means people are still using it ten years down the road! Still, I'm not as allergic to the XR name as I once was.

I do want to be careful that we're not accidentally creating a false association between the Khronos API and this one. With the existing mapping of OpenGL->WebGL I think it could be easy for people to assume that there was a pretty direct OpenXR->WebXR mapping. That won't be the case, even if there do end up being some structural similarities.

I also feel that we've managed to create a little bit of branding and buzz around WebVR which would be awkwardly reset with a name change.

With all that being said, if there was a large amount of support for a name change I wouldn't strenuously oppose it.

**Comment by AlbertoElias** [comment]
Yeah, I wasn't a big fan of XR at the beginning, but it has started to grow on me. When OpenXR was announced, I did understand that WebVR would be built on top of it, as it's currently built on top of OpenVR and the Oculus Runtime.

I just think it might be short-sighted for right as version 2 will work with what Microsoft calls Mixed Reality, so I think it will be confusing to call it WebVR now.

There has been quite a lot of buzz around WebVR, but I don't think we would lose that much due to a name change, specially as OpenXR is already creating buzz around XR.

Let's see if more people have an opinion

**Comment by toji** [comment]
5 months in it doesn't look like there's a lot of opinions to go around on this. :) Closing as a matter of housekeeping, but I wanted to mention that I think there's some value in fostering the idea of a "WebXR family of APIs" (or, alternatively, the "Immersive Web APIs"), which would include WebVR, WebAR, and any other related APIs that come forward. I think it's going to be impractical to let one spec grow indefinitely to meet the needs of an evolving ecosystem, so dividing modular bits of functionality into separate but interdependent specs appears desirable, and picking an overly broad term for one may prove harmful to the others.

Of course this is all academic at this point, but it does mean that I still don't see a compelling reason to move away from the name "WebVR" at this time.
