### ISSUE TITLE
Clarify behavior of browser window in VR

### ISSUE THREAD

**Issue by brianchirls** [w3c/webvr#244]
Oculus and Samsung browsers (and I believe pretty soon Chrome) have the ability to display a browser window in VR. So far these are only on mobile devices that don't have separate monitors (or do they?), but I can imagine this is a feature that may one day show up in desktop browsers as well.

This raises a few questions about how these browser windows might behave, especially on desktop:
- Can a browser tab be rendered on an external monitor and in VR at the same time?
- If so, what do you do about `document.hidden` when it's hidden on one and not the other?
- If so, are both views always the same dimensions? What happens when you resize the window on the external monitor?
- What do you do about devicePixelRatio? I don't believe there's currently an event to signal that the value might change.
- Are both views necessarily showing the same thing? If not, how do you render them differently?
- Should there be a boolean property somewhere that indicates whether the display/browser is capable of such a thing?
- Should there be another boolean property somewhere that indicates whether you are currently viewing a browser window in VR, and if so should there be another property that tells you which device you're on?

I can imagine some reasons why we'd want to leave this alone for now and just let the browsers sort out behavior without providing any information. But I can also imagine scenarios where it would be very useful to know these things.
- One just came up in Slack about the possibility of briefly exiting presentation to do something DOM-specific like filling out a form and requesting presentation again when you're done. This is only useful if you don't have to take off the headset.
- It is often useful on a monitor to render the HMD's view of a scene with head tracking, but I find it is annoying to see head tracking on a view rendered in a VR window.

**Comment by toji** [comment]
The majority of this, while it's VR-centric, isn't directly related to the WebVR spec and is more about UA behavior. There will need to be discussion and new spec built up around some of this, but it seems to me like the WebVR spec isn't the place for it. (A browser can be built in VR with no WebVR support, and it will still need to address these issues.) As a result I'm going to close this issue on this repo, though unfortunately I don't know what the appropriate venue is.

However, I do have a few thoughts off the top of my head on some of the items:

> Can a browser tab be rendered on an external monitor and in VR at the same time?

I've come to discover through various conversations that this is a far harder problem than I would have anticipated. Specifically, pretty much all of CSS is geared around the idea that the page is only being rendered for a single media at a time. I imagine that on desktops while you could launch WebVR content from either a 2D or VR version of the browser, individual pages will never appear in both at the same time. A "send to VR/send to Desktop" mechanism for tabs seems like a logical follow up.

That renders moot a couple of your other questions.

> Should there be another boolean property somewhere that indicates whether you are currently viewing a browser window in VR, and if so should there be another property that tells you which device you're on?

I definitely think there should be a way to detect that a page is being viewed in VR, at least as a CSS media query, possibly more. In terms of reporting what device the page is being viewed on, I think the appropriate mechanism is to say that if a page in being viewed on a VR device only that device should be reported by the API. If others were available when the page moved into VR all other devices besides the one displaying the page should be disconnected. (I can't imagine ANY scenario in which you'd be viewing a page in one headset and upon clicking a WebVR present button you'd want to have it start displaying on a different display.) This, at least, can be encoded into the spec.

> It is often useful on a monitor to render the HMD's view of a scene with head tracking, but I find it is annoying to see head tracking on a view rendered in a VR window.

My intent with the most recent magic window proposals (#237) is to allow the UA flexibility in determining how head tracking is surfaced to the magic window session. This means that on a mobile device the view could reflect "head tracking", while the same page viewed in VR could either be given no tracking or even a mode where tracking properly reflects the users viewpoint in relation to the canvas to create a punchthrough effect.

Mirroring is a different matter, but you should never see a mirrored view on a page in VR, since mirroring only makes sense while presenting.
