### ISSUE TITLE
getFrameData usage while not presenting inconsistent in 1.1 spec

### ISSUE THREAD

**Issue by klausw** [w3c/webvr#246]
The current 1.1 spec is inconsistent about how poses can be used while not presenting ("magic window" mode), it says:

> [...] Subsequent calls to getFrameData() MUST provide the same values until the next call to submitFrame(). Returns true if the the provided VRFrameData object was successfully updated, false otherwise.

However, it's only legal to call submitFrame while presenting (it requires VRLayerInit and related presentation-only setup), so as written the frame data could never be updated in magic window mode.

Suggestion: change this to explicitly state _The value returned will not change until JavaScript has returned control to the browser_, without mentioning submitFrame, this is what it already says in the getPose() API comment which is different from the text description following that.

Also, it's unclear if the intention is to permit use of getFrameData() from both within window.rAF and vrDisplay.rAF callbacks. The vrDisplay.rAF spec says it's _Functionally equivalent to window.requestAnimationFrame when the VRDisplay is not presenting_, but implementations that tie pose handling to vrDisplay.rAF specifically may not be able to provide poses easily for window.rAF callbacks. Can this be clarified? Either require getFrameData() to be used from a vrDisplay.rAF context (similar to submitFrame), or make it explicit that getFrameData should return reasonably-fresh poses for either window.rAF or vrDisplay.rAF while not presenting?

**Comment by ddorwin** [comment]
I believe we want to require that "getFrameData() to be used from a vrDisplay.rAF context" and not allow it to be used from window.rAF. This is consistent with the direction of the 2.0 spec.

**Comment by toji** [comment]
This was brought up on the most recent WebVR implementors call, and the consensus was that we all felt comfortable limiting `getFrameData()` to `vrDisplay.rAF` (This will more closely mimic the expected 2.0 behavior anyway). I'll put together a pull request for that today.

**Comment by toji** [comment]
Put up a pull request, pretty simple. Please take a look and chime in if there's anything you feel should be added or clarified.

**Comment by brianchirls** [comment]
It's still not clear to me why this is necessary, and it feels wrong. I often need to display a preview of the VR view in a window without presenting. For current mobile devices, this is a minor pain in the neck, but on desktop (will be testing this afternoon), it's going to require rendering at 90fps for a 60fps monitor. At best that's a waste of computing resources and battery (for laptops). As it is Firefox already has trouble getting the desktop view to display without major jank while presenting at 90fps.

**Comment by toji** [comment]
Hey @brianchirls, thanks for bringing up the concern. We could probably explain better.

In part this was necessary because, as Klaus pointed out, the spec text as it was written actually made magic window content impossible because you would never call `submitFrame` in that mode. We have seen while putting together our various implementations, however, that there's a need to clearly define when the pose is updated and when it can be queried (for example: Windows Mixed Reality can't deliver poses unless they're tied to active headset updates, from what I understand.) We've mostly considered it in the context of WebVR 2.0, and this is more-or-less bringing the restrictions that revision will put in place back to the 1.1 spec as a stop-gap.

As for your stated scenario, it's possible even with this restriction in place: To "preview the VR scene without presenting" (what we commonly refer to as "Magic Window" mode and which 2.0 will formalize as a "Non-exclusive session") you simply use `VRDisplay.requestAnimationFrame()` as normal without calling `requestPresent()`. This will run at the framerate of the main display (it's basically an alias for `window.requestAnimationFrame` at that point) so there's no extraneous frames produced.

A variant of that which may come up is the desire to render a secondary view of the scene on the external monitor which takes into account the device pose but isn't just a mirror of the headset view. You certainly _could_ render this in the `VRDisplay.rAF` loop and just eat the cost of the extra frames, but a more economical approach would be to cache the pose matrix every `VRDisplay.rAF` cycle and run a separate `window.rAF` loop that renders with whatever the latest cached pose is. Fair warning: This can lead to a potentially janky performance pattern where 2/3 of the VR frames have to share GPU time with a monitor-bound frame, while the other 1/3 do not. How exactly that will manifest depends on your scene but it could range from "unnoticeable" for lightweight scenes to "our pose prediction algorithms are completely broken now" for heavier content. In some cases in may actually be better to eat the extra frames for the sake of workload consistency. Your mileage may vary.
