### ISSUE TITLE
Possible to soften DEPRECATED language in the 1.1 spec?

### ISSUE THREAD

**Issue by larsbergstrom** [w3c/webvr#288]
Until the next evolution of the WebVR specification is named and ratified, would it be possible to remove or soften the "Deprecated API" language in the 1.1 spec?
 https://github.com/w3c/webvr/blob/master/spec/1.1/index.bs#L39

The text following that notice pointing out that there are substantial changes and additions underway is fine, but it's not clear to me at this point what the timeline for that is, much less what the browser engine implementation and rollout plans will be (though certainly there will be a polyfill in place earlier, which https://github.com/mozilla/webxr-polyfill shows we should be able to do).

The current version of the specification was already seeing fairly widespread usage, especially on mobile, before Mozilla and Microsoft turned it on by default (previously working via the polyfill), and the current text is leading to tool vendor and developer confusion. I cannot speak for other engines, but I know that Mozilla is committed to supporting this specification either directly or via polyfill until such time as that usage drops below an acceptable threshold.

Thanks!

cc @kearwood @cvan

**Comment by juj** [comment]
The "deprecated API" text was added by @toji in this commit: https://github.com/w3c/webvr/commit/9f19295a067713d88e57aaea6ebbb7ab5914023f#diff-8a45dbf79f7f093d5df08567a0a2ab50R39, and it looks like a janitorial change to organize content better rather than something that was a result from conversation between vendors.

It would be best to change the "Deprecated API" to read "latest stable version", since WebVR 1.1 spec is what vendors are currently shipping, and newer versions are not yet finalized. Does that sound sensible?

**Comment by kearwood** [comment]
At least for the Firefox browser, our intent is not to immediately "deprecate" the API, even after WebVR 2.0 has shipped.  We expect to maintain support for WebVR 1.1 until usage of the older API drops off, which could be some time later.  Once WebVR 2.0 has been implemented and shipped in release channels, I wouldn't be against stating that it is now "deprecated" and that new content should be written against the new spec.

Mozilla is also open to sharing a "WebVR 1.1 on 2.0" polyfill to help sites make the transition.

**Comment by juj** [comment]
There are developers who are asking how to get onboard with developing WebVR in the browsers, and they are surprised by there being a WebVR 1.1 spec that is being called ["Deprecated API"](https://w3c.github.io/webvr/spec/1.1/), and a WebVR 2.0 draft that is called ["DO NOT IMPLEMENT"](https://w3c.github.io/webvr/spec/latest/) and big grey `"unstable"` watermarks on the background. I am not sure where to point these developers to.

The text "`Deprecated API`" was added too soon. The site https://webvr.info/developers/ specifies a list of compatible browsers in a high spirited "call to action" manner, but does not help specifying what WebVR these browsers actually are compatible with. Let's get up from this in-between specs vacuum, we need to have the "latest version" pointed to clearly. Added PR #288 to resolve this.

Also, a WebVR 1.1 to WebVR 2.0 migration guide would be good, since it looks like no dev channel yet ships any form of WebVR 2.0, so the bleeding edge curious developers will need to use a WebVR 1.1 version. They will need to at some point understand how to migrate to the new version, so it would be good to have means for them to do so.
