### ISSUE TITLE
Clarify what happens with `VRLayer` is missing a `source`

### ISSUE THREAD

**Issue by brianchirls** [w3c/webvr#58]
Right now the spec does not state how to handle a `VRLayer` passed into `requestPresent` without a `source` property or what to do if that `source` is not valid. According to @toji, Chrome resolves the promise and [does nothing](https://chromium.googlesource.com/experimental/chromium/src/+/40a4708bffa96e6b07d155a122f4d3a1e80ea97f%5E%21/#F60).

I think it makes sense to reject the promise, which would be more helpful for debugging that failing silently. Either way, the behavior should be documented.

**Comment by kearwood** [comment]
I suppose a use case that this may serve is that a site wishes to keep holding on to a VRDisplay by keeping presentation active, but does not have frames to submit.  In this case, perhaps the browser could display some indication that the site is "loading" or "busy"?

Alternately, this could indicate that the frame is completely black...

Or, we could simply require source instead of making it optional?

Any preferences here?

**Comment by toji** [comment]
Thinking about the site transition case, I think it would be useful to have this show black or a spinner of some sort. Assuming that VR presentation is only allowed to begin on a user gesture, I was thinking that entering VR automatically on page navigation would involve firing `vrdisplayactivate` early in the page lifetime, which would count as a user gesture and allow presentation to start. The fact is, though, that many pages will need to do some heavier loading than can reasonably be completed before an event like that fires. The best practice would be to have the page build and display it's own lightweight splash or loading screen, but that's often seen as a polish item rather than a hard requirement by devs.

Having a layer-less present "reserve" the ability for the page to present seems like a good idea in that context. Black is fine, generic loading indicator is maybe better? Not sure. The big question I have then is does the page need to continue calling submitFrame? If the page isn't actively submitting anything that feels like a weird thing to do.

Of course, if we want to avoid that can of worms altogether making it required (at least for v1) is good by me too.

**Comment by toji** [comment]
At this point the layering system has been reworked, and the new structure does not allow a `VRWebGLLayer` to be constructed without a valid context, making this issue moot.
